FROM node:20.18.0-alpine3.20
EXPOSE 8080
ENV DB_HOST= "mysql"
RUN mkdir /opt/server
WORKDIR /opt/server
COPY package.json . 
COPY *.js .
RUN npm install
CMD ["node","index.js"]


# Before implementing best  practices this image size ia aroudn 1.1GB

# FROM node:20
# EXPOSE 8080
# ENV DB_HOST= "mysql"
# # where mysql is the name of the mysql container
# RUN mkdir /opt/server
# WORKDIR /opt/server
# COPY package.json . 
# COPY *.js .
# # . indicates current folder
# RUN npm install
# CMD ["node","index.js"]
# # we can use ENTRYPOINT instead of CMD once testing is done because we cannot debug


