FROM node:20 AS node-build
WORKDIR /opt/server
COPY package.json . && \
    *.js .
RUN npm install



FROM node:20.18.0-alpine3.20
EXPOSE 8080
ENV DB_HOST="mysql"
RUN addgroup -S expense && adduser -S expense -G expense && \
    mkdir /opt/server && \
    chown -R expense:expense /opt/server
WORKDIR /opt/server
COPY --from=node-build /opt/server /opt/server
USER expense
CMD ["node","index.js"]


# # Before implementing best practices this image size ia around 1.1GB

# FROM node:20
# EXPOSE 8080 
# # this does not open port. It is for information purpose only
# ENV DB_HOST="mysql"
# # where mysql is the name of the mysql container
# RUN mkdir /opt/server
# WORKDIR /opt/server
# COPY package.json . 
# COPY *.js .
# # . indicates current folder which is /opt/server
# RUN npm install
# CMD ["node","index.js"]
# # we can use ENTRYPOINT instead of CMD once testing is done because we cannot debug


