FROM node:20
EXPOSE 8080
ENV DB_HOST= "mysql"
# where mysql is the name of the mysql container
RUN mkdir /opt/server
WORKDIR /opt/server
COPY package.json . 
COPY *.js .
# . indicates current folder
RUN npm install
CMD ["node","index.js"]
# we can use ENTRYPOINT instead of CMD once testing is done because we cannot debug



