FROM mysql:8.0
ENV MYSQL_ROOT_PASSWORD=ExpenseApp@1 
    # MYSQL_DATABASE=transactions \
    # MYSQL_USER= expense \
    # MYSQL_PASSWORD=ExpenseApp@1
# to add a group and user for debian
RUN groupadd expense && \ 
    useradd -g expense expense && \
    chown -R expense:expense /var/lib/mysql /var/run/mysqld /docker-entrypoint-initdb.d
ADD scripts/*.sql /docker-entrypoint-initdb.d
USER expense